service: babel-example

plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x

functions:
  all:
    handler: src/functions/all.handler
    events:
      - http:
          method: get
          path: all
          integration: lambda
